"""empty message

Revision ID: 114c54835515
Revises: a596a46587c9
Create Date: 2022-07-20 10:09:45.664733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114c54835515'
down_revision = 'a596a46587c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=700),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.String(length=700),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
