"""empty message

Revision ID: 7d262d169760
Revises: f465becdf7ed
Create Date: 2022-07-20 10:13:13.993140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d262d169760'
down_revision = 'f465becdf7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=False)
    # ### end Alembic commands ###
