"""empty message

Revision ID: f465becdf7ed
Revises: 114c54835515
Create Date: 2022-07-20 10:12:10.982521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f465becdf7ed'
down_revision = '114c54835515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.String(length=1500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=700),
               existing_nullable=False)
    # ### end Alembic commands ###
